### ISSUE TITLE
Seal failing on empty input file

### ISSUE THREAD

**Issue by bit-bender** [NationalSecurityAgency/kmyth#13]
Trying to seal an empty input file results in:

> touch test.in
> ./bin/kmyth-seal -i test.in -o test.ski -v

kmyth-0.0.0 DEBUG - src/util/tpm2_config_tools.c(tpm2_init_sapi:162) ABI version is 1.2.1.108
kmyth-0.0.0 DEBUG - src/util/tpm2_config_tools.c(tpm2_init_sapi:195) initialized SAPI context
.
.
.
kmyth-0.0.0 DEBUG - src/util/aes_gcm.c(aes_gcm_encrypt:23) AES/GCM encryption starting
kmyth-0.0.0 ERROR - src/util/aes_gcm.c(aes_gcm_encrypt:35) no input data ... exiting
kmyth-0.0.0 ERROR - src/util/tpm2_kmyth_seal.c(kmyth_encrypt_data:717) error encrypting data ... exiting
kmyth-0.0.0 ERROR - src/util/tpm2_kmyth_seal.c(kmyth_wrap_input:675) unable to encrypt (wrap) data ... exiting
kmyth-0.0.0 ERROR - src/util/tpm2_kmyth_seal.c(tpm2_kmyth_seal:246) kmyth_wrap_input() call failed ... exiting
double free or corruption (out)
Aborted (core dumped)

**Comment by b-carr** [comment]
Looking more closely at the code, I think by putting the check in `kmyth_wrap_input` in `src/util/tpm2_kmyth_seal.c` is the best place from the library perspective.

The `src/seal/main.c` executable should also check before doing all the TPM work.

**Comment by wmillstone** [comment]
The first fix seems easy enough, but for the check in `src/seal/main.c` it looks like we would want to make a call to `read_arbitrary_file()` to get the data length. This is already done later on, in `kmyth_wrap_input` in `src/util/tpm2_kmyth_seal.c`. Doing this twice seems like it may be redundant if we are not passing along the output values.

**Comment by b-carr** [comment]
That's a good point. For now let's just fix `kmyth_wrap_input`. I still don't like the idea of doing all that TPM work just to find out the file has zero size, but it's going to be a bigger job to do the filesize check reasonably, so we can keep it in mind for future work if we decide it's worthwhile.

**Comment by PeterHamilton** [comment]
I'm a bit late to the discussion but I figured this was relevant.

I'm adding error handling to `read_arbitrary_file` in `src/util/tpm2_kmyth_io.c`. A file size of 0 bytes may cause `malloc` to return `NULL`, which is indistinguishable from an allocation failure. Right now (with my edits) this returns 1, which would get caught and handled right before the fix added in #26, resurrecting the original issue.

I can change this so that `read_arbitrary_file` just short circuits and returns early when it encounters a 0 byte file, so that the fix in #26 still applies as expected. Would that be the preferred error flow here?

On the opposite end of spectrum, what is the maximum file size that should be supported? We could just rely on `malloc` erroring out in that case but that may not be sufficient. Is there a reasonable maximum threshold? Or is this out-of-scope here anyway since the user is supplying the file?
